-- MySQL Script generated by MySQL Workbench
-- Ср. 18 мая 2016 16:00:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bug_tracker_for_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bug_tracker_for_bd` ;

-- -----------------------------------------------------
-- Schema bug_tracker_for_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bug_tracker_for_bd` ;
SHOW WARNINGS;
USE `bug_tracker_for_bd` ;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projects` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT(11) NOT NULL,
  `Name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `project_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_files` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `project_files` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project` INT(11) NULL,
  `file` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `errors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `errors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `file` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fixed_errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fixed_errors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fixed_errors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `error` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `role` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users_role_prog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_role_prog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users_role_prog` (
  `id` INT(11) NOT NULL,
  `id_user` INT(11) NULL,
  `id_role` INT(11) NULL,
  `id_prog` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `users`
-- -----------------------------------------------------
START TRANSACTION;
USE `bug_tracker_for_bd`;
INSERT INTO `users` (`id`, `name`, `password`) VALUES (1, 'developer', 'developer');
INSERT INTO `users` (`id`, `name`, `password`) VALUES (2, 'tester', 'tester');

COMMIT;


-- -----------------------------------------------------
-- Data for table `projects`
-- -----------------------------------------------------
START TRANSACTION;
USE `bug_tracker_for_bd`;
INSERT INTO `projects` (`id`, `Name`) VALUES (1, 'proj1');
INSERT INTO `projects` (`id`, `Name`) VALUES (2, 'proj2');

COMMIT;


-- -----------------------------------------------------
-- Data for table `role`
-- -----------------------------------------------------
START TRANSACTION;
USE `bug_tracker_for_bd`;
INSERT INTO `role` (`id`, `name`) VALUES (1, 'developer');
INSERT INTO `role` (`id`, `name`) VALUES (2, 'tester');

COMMIT;


-- -----------------------------------------------------
-- Data for table `users_role_prog`
-- -----------------------------------------------------
START TRANSACTION;
USE `bug_tracker_for_bd`;
INSERT INTO `users_role_prog` (`id`, `id_user`, `id_role`, `id_prog`) VALUES (1, 1, 1, 1);
INSERT INTO `users_role_prog` (`id`, `id_user`, `id_role`, `id_prog`) VALUES (2, 1, 1, 2);
INSERT INTO `users_role_prog` (`id`, `id_user`, `id_role`, `id_prog`) VALUES (3, 2, 2, 1);
INSERT INTO `users_role_prog` (`id`, `id_user`, `id_role`, `id_prog`) VALUES (4, 2, 2, 2);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
